
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('studio', {
  appInfo: () => ipcRenderer.invoke('app-info'),
  getGitOverview: () => ipcRenderer.invoke('git-overview'),
  gitPush: () => ipcRenderer.invoke('git-push'),
  gitPull: () => ipcRenderer.invoke('git-pull'),
  openGitHub: () => ipcRenderer.invoke('open-github'),
  getDevelopmentPartner: () => ipcRenderer.invoke('get-development-partner'),
  status: () => ipcRenderer.invoke('status'),
  chooseUpdatePackage: () => ipcRenderer.invoke('choose-update-package'),
  inspectUpdatePackagePath: packagePath => ipcRenderer.invoke('inspect-update-package-path', packagePath),
  consumeLaunchPackage: () => ipcRenderer.invoke('consume-launch-package'),
  installUpdatePackage: () => ipcRenderer.invoke('install-update-package'),
  openPackageHistory: () => ipcRenderer.invoke('open-package-history'),
  createForgeTestPackage: () => ipcRenderer.invoke('create-forge-test-package'),
  getUpdateInboxStatus: () => ipcRenderer.invoke('get-update-inbox-status'),
  openUpdateInbox: () => ipcRenderer.invoke('open-update-inbox'),
  scanUpdateInboxNow: () => ipcRenderer.invoke('scan-update-inbox-now'),
  onUpdateInboxEvent: cb => ipcRenderer.on('update-inbox-event', (_e, event) => cb(event)),
  buildManifest: () => ipcRenderer.invoke('build-manifest'),
  getExplorer: () => ipcRenderer.invoke('get-explorer'),
  listTransactions: () => ipcRenderer.invoke('list-transactions'),
  undoTransaction: id => ipcRenderer.invoke('undo-transaction', id),
  scanMisplaced: () => ipcRenderer.invoke('scan-misplaced'),
  scanCleaner: () => ipcRenderer.invoke('scan-cleaner'),
  exportCleanerAnalysis: () => ipcRenderer.invoke('export-cleaner-analysis'),
  moveFile: item => ipcRenderer.invoke('move-file', item),
  quarantineFile: item => ipcRenderer.invoke('quarantine-file', item),
  restoreQuarantined: manifestPath => ipcRenderer.invoke('restore-quarantined', manifestPath),
  exportReport: () => ipcRenderer.invoke('export-report'),
  exportAiSyncPackage: () => ipcRenderer.invoke('export-ai-sync-package'),
  adbDevices: () => ipcRenderer.invoke('adb-devices'),
  adbConnectWireless: address => ipcRenderer.invoke('adb-connect-wireless', address),
  deployAppOneClick: () => ipcRenderer.invoke('deploy-app-one-click'),
  publishApkFree: () => ipcRenderer.invoke('publish-apk-free'),
  openPath: p => ipcRenderer.invoke('open-path', p),
  npmInstall: () => ipcRenderer.invoke('run-studio-npm-install'),
  runDoctor: () => ipcRenderer.invoke('run-doctor'),
  buildWeb: () => ipcRenderer.invoke('build-web'),
  syncAndroid: () => ipcRenderer.invoke('sync-android'),
  buildApk: () => ipcRenderer.invoke('build-apk'),
  installApk: () => ipcRenderer.invoke('install-apk'),
  buildDependencyGraph: () => ipcRenderer.invoke('build-dependency-graph'),
  projectHealth: () => ipcRenderer.invoke('project-health'),
  previewFile: relativePath => ipcRenderer.invoke('preview-file', relativePath),
  createCleanupPlan: selectedPaths => ipcRenderer.invoke('create-cleanup-plan', selectedPaths),
  executeCleanupPlan: plan => ipcRenderer.invoke('execute-cleanup-plan', plan),
  listRecoveryPoints: () => ipcRenderer.invoke('list-recovery-points'),
  restorePackageInstallation: packageId => ipcRenderer.invoke('restore-package-installation', packageId),
  runSelfTests: () => ipcRenderer.invoke('run-self-tests'),
  openRecoveryFolder: () => ipcRenderer.invoke('open-recovery-folder'),
  openQuarantineFolder: () => ipcRenderer.invoke('open-quarantine-folder'),
  buildProjectKnowledge: () => ipcRenderer.invoke('build-project-knowledge'),
  getProjectKnowledge: () => ipcRenderer.invoke('get-project-knowledge'),
  listManifestHistory: () => ipcRenderer.invoke('list-manifest-history'),
  compareManifestSnapshots: (newerId, olderId) => ipcRenderer.invoke('compare-manifest-snapshots', newerId, olderId),
  openKnowledgeFolder: () => ipcRenderer.invoke('open-knowledge-folder'),
  getProjectBrain: () => ipcRenderer.invoke('get-project-brain'),
  searchProjectBrain: (query, mode = 'search', limit = 200) => ipcRenderer.invoke('search-project-brain', query, mode, limit),
  getProjectBrainFile: query => ipcRenderer.invoke('get-project-brain-file', query),
  openProjectBrainFolder: () => ipcRenderer.invoke('open-project-brain-folder'),
  buildProjectDNA: () => ipcRenderer.invoke('build-project-dna'),
  getProjectDNA: () => ipcRenderer.invoke('get-project-dna'),
  openAIContext: () => ipcRenderer.invoke('open-ai-context'),
  getAIWorkspace: () => ipcRenderer.invoke('get-ai-workspace'),
  copyAIContext: target => ipcRenderer.invoke('copy-ai-context', target),
  exportAIPackage: () => ipcRenderer.invoke('export-ai-package'),
  showAIContext: () => ipcRenderer.invoke('show-ai-context'),
  onLog: cb => ipcRenderer.on('log', (_e, text) => cb(text))
});
